name: memorybox2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"








dependencies:
  flutter:
    sdk: flutter

  # Widgets ets.
  flutter_svg: ^0.23.0+1
  file_picker: ^4.2.6
  image_picker: ^0.8.4+4
  share: ^2.0.4
  # Services
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  permission_handler:
  open_file:
  external_path: ^1.0.1
  path_provider:
  record:
  audioplayers:
  rive: ^0.8.1
  uuid: ^3.0.5
  get_it:
  # Firebase dependencies
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.0
  firebase_storage:


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/backgroundVector/
    - assets/animations/


  fonts:
    - family: TTNorms-Bold
      fonts:
        - asset: assets/fonts/TTNorms-Bold.ttf
    - family: TTNorms-Medium
      fonts:
        - asset: assets/fonts/TTNorms-Medium.ttf
    - family: TTNorms-Regular
      fonts:
        - asset: assets/fonts/TTNorms-Regular.ttf
